version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '07:30'
      timezone: 'Asia/Tokyo'

  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: monthly
      time: '07:30'
      timezone: 'Asia/Tokyo'
    groups:
      npm-major-upgrades:
        update-types:
          - 'major'
      npm-minor-upgrades:
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '@playwright/test'
